I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/endings/escape.rpy", line 1223, in script
    gallcg "{color=#fff}Wow."
Exception: Sayer 'gallcg' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/endings/escape.rpy", line 1223, in script
    gallcg "{color=#fff}Wow."
  File "/Users/ayanafridkin/Downloads/renpy-8.3.7-sdk/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/Users/ayanafridkin/Downloads/renpy-8.3.7-sdk/renpy/ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/ayanafridkin/Downloads/renpy-8.3.7-sdk/renpy/ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'gallcg' is not defined.

macOS-11.6-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
Aperture Dating Simulator 1.1.3.beta
Mon Aug 18 16:15:35 2025
