I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/endings/battle.rpy", line 77, in script
    "BOOTING{cps=1}..."
  File "game/story/endings/battle.rpy", line 77, in script
    "BOOTING{cps=1}..."
  File "game/screens.rpy", line 108, in execute
    screen say(who, what):
  File "game/screens.rpy", line 108, in execute
    screen say(who, what):
  File "game/screens.rpy", line 133, in execute
    if battle == False:
  File "game/screens.rpy", line 133, in <module>
    if battle == False:
NameError: name 'battle' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "game/story/endings/battle.rpy", line 77, in script
    "BOOTING{cps=1}..."
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/story/endings/battle.rpy", line 77, in script
    "BOOTING{cps=1}..."
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\character.py", line 1470, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\character.py", line 1117, in do_display
    display_say(who,
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\character.py", line 749, in display_say
    what_text = renpy.display.screen.get_widget(what_text[0], what_text[1], what_text[2])
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\screen.py", line 1541, in get_displayable
    screen.update()
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\screen.py", line 700, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 108, in execute
    screen say(who, what):
  File "game/screens.rpy", line 108, in execute
    screen say(who, what):
  File "game/screens.rpy", line 133, in execute
    if battle == False:
  File "game/screens.rpy", line 133, in <module>
    if battle == False:
NameError: name 'battle' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Aperture Dating Simulator 0.3.1alpha
Sat Jun 21 22:51:22 2025
