I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/endings/esthertrue.rpy", line 310, in script
    nb "Finally, you reach the summit, exhausted."
Exception: Sayer 'nb' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/endings/esthertrue.rpy", line 310, in script
    nb "Finally, you reach the summit, exhausted."
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'nb' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Aperture Dating Simulator 1.1.0pt
Fri Sep  5 11:48:53 2025
