I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/endings/daythirteen.rpy", line 756, in script
    scene office hell
Exception: Image 'office' does not accept attributes 'hell'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/endings/daythirteen.rpy", line 756, in script
    scene office hell
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1258, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1087, in show_imspec
    renpy.config.show(name,
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\image.py", line 722, in _duplicate
    args.extraneous()
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'office' does not accept attributes 'hell'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Aperture Dating Simulator 1.0.7
Thu Sep  4 12:57:07 2025
