I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/endings/daythirteen.rpy", line 239, in script
    show gore sus
Exception: Image 'gore' does not accept attributes 'sus'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/endings/daythirteen.rpy", line 239, in script
    show gore sus
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1087, in show_imspec
    renpy.config.show(name,
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'gore' does not accept attributes 'sus'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Aperture Dating Simulator 0.7.0alpha
Mon Jul 14 15:39:24 2025
