I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/endings/daythirteen.rpy", line 243, in script
    if unknown_lock:
  File "game/story/endings/daythirteen.rpy", line 243, in <module>
    if unknown_lock:
NameError: name 'unknown_lock' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/endings/daythirteen.rpy", line 243, in script
    if unknown_lock:
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\python.py", line 1215, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\python.py", line 1208, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/story/endings/daythirteen.rpy", line 243, in <module>
    if unknown_lock:
NameError: name 'unknown_lock' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Aperture Dating Simulator 0.4.0alpha
Mon Jun 23 01:37:27 2025
