I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/week two/tenthday.rpy", line 844, in script
    m "Before you know it, it's almost 16:00, and it's time to clock out."
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/week two/tenthday.rpy", line 844, in script
    m "Before you know it, it's almost 16:00, and it's time to clock out."
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'm' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Aperture Dating Simulator 0.1.8alpha
Tue Jun  3 12:30:58 2025
